exports.compositoresListPage = function (slist, d) {
    var pagHTML = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <link rel="icon" href="favicon.png"/>
                <link rel="stylesheet" href="w3.css"/>
                <title>Compositores Management</title>
            </head>
            <body>
                <div class="w3-card-4">
                    <header class="w3-container w3-teal">
                        <h1>Lista de Compositores
                            <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                        </h1>
                    </header>
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th><th>Periodo</th>
                            <th>Actions</th>
                        </tr>
                    `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        <a href="/periodos/${slist[i].periodo.id}">
                            ${slist[i].periodo.nome}
                        </a>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }
    pagHTML += `
                </table>
            </div>
                <footer class="w3-container w3-teal">
                    <address>Gerado por aluno::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.mainPage = function (d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Main Page</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>Menu</h1>
                </header>
            <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Páginas</th>
                </tr>
                <tr>
                    <td>
                        <a href="/compositores">Compositores</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="/periodos">Periodos</a>
                    </td>
                </tr>
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                 </footer>
            </div>
        </body>
    </html>
    `
}


exports.compositorFormPage = function (d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.compositorFormEditPage = function (c, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${c.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${c.nome}"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${c.bio}"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${c.periodo}"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${c.dataNasc}"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${c.dataObito}"/>
                        </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
                    `
    return pagHTML
}
// ---------------Compositor Page--------------------------------
// Change and adapt to current dataset...
exports.compositorPage = function (compositor, d) {
    var pagHTML = `
    <html>
    <head>
        <title>Compositor: ${compositor.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Compositor ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${compositor.nome}</li>
                    <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                    <li><b>Data de óbito: </b> ${compositor.dataObito}</li>
                    <li><b>Periodo: </b> <a href="/periodos/${compositor.periodo.id}">${compositor.periodo.nome}</li>
                    <li><b>Biografia: </b> ${compositor.bio}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `

    pagHTML += `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodosListPage = function (slist, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodos Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Lista de Periodos
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th><th>Name</th>
                            <th>Actions</th>
                        </tr>
                `
    for (let i = 0; i < slist.length; i++) {
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/periodos/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }
    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <address>Gerado por aluno::EngWeb2024 em ${d} - [<a href="/">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}

exports.periodoPage = function (periodo, d) {
    var pagHTML = `
    <html>
    <head>
        <title>Periodo: ${periodo.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Periodo ${periodo.nome}</h1>
            </header>
            <div class="w3-container">
                <h3> Compositores: </h3>
                <table class="w3-table-all">
                    <tr>
                        <th>Id</th><th>Nome</th>
                    </tr>`

    periodo.compositores.forEach(compositor => {
        pagHTML += `
            <tr>
                <td>
                    ${compositor.id}
                </td>
                <td>
                    <a href= "/compositores/${compositor.id}"> ${compositor.nome}</a>
                </td>
            </tr>
        `
    })
    pagHTML += `
                </table>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `

    pagHTML += `</ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

exports.periodoFormPage = function (d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <address>Gerado por galuno::EngWeb2024 em ${d} - [<a href="/periodos">Voltar</a>]</address>
                </footer>
            
            </div>
    `
}

exports.compositorFormPage = function (d) {
    return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositor Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Compositor Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Bio</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo"/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Data de Óbito</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            
            </div>
    `
}

exports.periodoFormEditPage = function (p, d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periodo Edit Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Periodo Edit Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${p.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${p.nome}"/>
                        </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
                    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function (errorMessage, d) {
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}